In [1]:
import tensorflow as tf
import pandas as pd
import os
import numpy as np
import datetime as dt
from random import seed
from tensorflow.keras import models
from tensorflow.keras import layers
from tensorflow.keras import backend as K
tf.compat.v1.experimental.output_all_intermediates(True)

In [2]:
seed(36)

In [3]:
BASE_DIR_PATH = '/Users/neilb/Documents/dsci_thesis/Datasets'
DATASET_FILE = os.path.join(BASE_DIR_PATH, 'compiled_data.csv')

In [4]:
BASE_DIR_PATH = '/Users/neilb/Documents/dsci_thesis/Datasets'
DATASET_FILE = os.path.join(BASE_DIR_PATH, 'compiled_data.csv')

In [5]:
df = pd.read_csv(DATASET_FILE)
df.head(10)

,Unnamed: 0,Rainfall_Aries,Rainfall_Boso,Rainfall_Campana,Rainfall_Nangka,Rainfall_Oro,Waterlevel_Sto_Nino,Waterlevel_Montalban,Discharge_Sto_Nino,Discharge_San_Jose,Cross_Section_Sto_Nino,Cross_Section_Montalban,Velocity_Sto_Nino,Velocity_Montalban,datetime,t,x
0,0,0,1,1,0,0,12.53,21.39,19186.201907,35800.887186,826.98,641.7,23.200322,55.790692,2017-01-01 00:00:00,0.0,14420
1,1,0,0,0,1,0,12.53,21.39,19186.201907,35800.887186,826.98,641.7,23.200322,55.790692,2017-01-01 01:00:00,3600.0,14420
2,2,0,0,0,0,0,12.53,21.39,19186.201907,35800.887186,826.98,641.7,23.200322,55.790692,2017-01-01 02:00:00,7200.0,14420
3,3,0,0,1,1,0,12.53,21.39,19186.201907,35800.887186,826.98,641.7,23.200322,55.790692,2017-01-01 03:00:00,10800.0,14420
4,4,0,0,0,0,0,12.53,21.39,19186.201907,35800.887186,826.98,641.7,23.200322,55.790692,2017-01-01 04:00:00,14400.0,14420
5,5,0,0,1,0,0,12.53,21.39,19186.201907,35800.887186,826.98,641.7,23.200322,55.790692,2017-01-01 05:00:00,18000.0,14420
6,6,0,0,0,0,0,12.53,21.39,19186.201907,35800.887186,826.98,641.7,23.200322,55.790692,2017-01-01 06:00:00,21600.0,14420
7,7,0,0,0,0,0,12.53,21.39,19186.201907,35800.887186,826.98,641.7,23.200322,55.790692,2017-01-01 07:00:00,25200.0,14420
8,8,0,0,1,0,0,12.53,21.39,19186.201907,35800.887186,826.98,641.7,23.200322,55.790692,2017-01-01 08:00:00,28800.0,14420
9,9,6,5,20,4,20,12.53,21.39,19186.201907,35800.887186,826.98,641.7,23.200322,55.790692,2017-01-01 09:00:00,32400.0,14420

In [6]:
df = df[['Rainfall_Aries', 'Rainfall_Boso', 'Rainfall_Campana', 'Rainfall_Nangka', 'Rainfall_Oro', 'Waterlevel_Sto_Nino']]
df.head(10)

,Rainfall_Aries,Rainfall_Boso,Rainfall_Campana,Rainfall_Nangka,Rainfall_Oro,Waterlevel_Sto_Nino
0,0,1,1,0,0,12.53
1,0,0,0,1,0,12.53
2,0,0,0,0,0,12.53
3,0,0,1,1,0,12.53
4,0,0,0,0,0,12.53
5,0,0,1,0,0,12.53
6,0,0,0,0,0,12.53
7,0,0,0,0,0,12.53
8,0,0,1,0,0,12.53
9,6,5,20,4,20,12.53

In [7]:
# Splitting for time series: split into 70-20-10
n = len(df)
train_df = df[0:int(n*0.7)]
val_df = df[int(n*0.7):int(n*0.9)]
test_df = df[int(n*0.9):]

In [8]:
class WindowGenerator():
    def __init__(self, input_width, label_width, shift, train_df=train_df, val_df=val_df, test_df=test_df, label_columns=None):
        # Store the raw data.
        self.train_df = train_df
        self.val_df = val_df
        self.test_df = test_df

        # Work out the label column indices.
        self.label_columns = label_columns
        if label_columns is not None:
            self.label_columns_indices = {name: i for i, name in enumerate(label_columns)}
        self.column_indices = {name: i for i, name in enumerate(train_df.columns)}

        # Work out the window parameters.
        self.input_width = input_width
        self.label_width = label_width
        self.shift = shift

        self.total_window_size = input_width + shift

        self.input_slice = slice(0, input_width)
        self.input_indices = np.arange(self.total_window_size)[self.input_slice]

        self.label_start = self.total_window_size - self.label_width
        self.labels_slice = slice(self.label_start, None)
        self.label_indices = np.arange(self.total_window_size)[self.labels_slice]

    def __repr__(self):
        return '\n'.join([
            f'Total window size: {self.total_window_size}',
            f'Input indices: {self.input_indices}',
            f'Label indices: {self.label_indices}',
            f'Label column name(s): {self.label_columns}'])

    def split_window(self, features):
        inputs = features[:, self.input_slice, :]
        labels = features[:, self.labels_slice, :]
        if self.label_columns is not None:
            labels = tf.stack([labels[:, :, self.column_indices[name]] for name in self.label_columns], axis=-1)

        # Slicing doesn't preserve static shape information, so set the shapes
        # manually. This way the `tf.data.Datasets` are easier to inspect.
        inputs.set_shape([None, self.input_width, None])
        labels.set_shape([None, self.label_width, None])

        return inputs, labels
    
    # Creating tf datasets for more convenient use and integration into model in the future
    def make_dataset(self, data):
        data = np.array(data, dtype=np.float32)
        ds = tf.keras.utils.timeseries_dataset_from_array(
            data=data,
            targets=None,
            sequence_length=self.total_window_size,
            sequence_stride=1,
            shuffle=True,
            batch_size=32,)

        ds = ds.map(self.split_window)

        return ds
    
    # properties to access them as tf datasets
    @property
    def train(self):
        return self.make_dataset(self.train_df)

    @property
    def val(self):
        return self.make_dataset(self.val_df)

    @property
    def test(self):
        return self.make_dataset(self.test_df)

    @property
    def example(self):
        """Get and cache an example batch of `inputs, labels` for plotting."""
        result = getattr(self, '_example', None)
        if result is None:
            # No example batch was found, so get one from the `.train` dataset
            result = next(iter(self.train))
            # And cache it for next time
            self._example = result
        return result

In [9]:
# The wide window uses independent hours of data as input to predict the water level of the next hour
# Here, the prediction is done on 6 hours
# This is used for Dense and Recurrent Neural Networks
wide_window = WindowGenerator(
        input_width=6, label_width=6, shift=1,
        label_columns=['Waterlevel_Sto_Nino']
    )

wide_window

Total window size: 7
Input indices: [0 1 2 3 4 5]
Label indices: [1 2 3 4 5 6]
Label column name(s): ['Waterlevel_Sto_Nino']

In [10]:
# The conv window is used for the Convolutional Neural Netwrok
# 6 consecutive hours of data are used together to make predictions one hour into the future
CONV_WIDTH = 6
conv_window = WindowGenerator(
        input_width=CONV_WIDTH,
        label_width=1,
        shift=1,
        label_columns=['Waterlevel_Sto_Nino']
    )

conv_window

Total window size: 7
Input indices: [0 1 2 3 4 5]
Label indices: [6]
Label column name(s): ['Waterlevel_Sto_Nino']

In [11]:
def r_square(y_true, y_pred):
    x = y_true
    y = y_pred
    mx = K.mean(x, axis=0)
    my = K.mean(y, axis=0)
    xm, ym = x - mx, y - my
    r_num = K.square(K.sum(xm * ym))
    x_square_sum = K.sum(xm * xm)
    y_square_sum = K.sum(ym * ym)
    r_den = (x_square_sum * y_square_sum) + K.epsilon()
    
    r = r_num / r_den
    return r

In [12]:
def NSE(y_true, y_pred):
    '''
    This is the Nash-Sutcliffe Efficiency Coefficient
    '''
    y_pred = K.flatten(y_pred)
    y_true = K.flatten(y_true)

    
    SS_res =  K.sum(K.square(y_true - y_pred)) 
    SS_tot = K.sum(K.square(y_true - K.mean(y_true))) 
    
    return ( 1 - SS_res/(SS_tot + K.epsilon()) )

In [13]:
# For easy compiling and fitting of different models
MAX_EPOCHS = 20

def compile_and_fit(model, window, patience=2):
    early_stopping = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=patience, mode='min')

    model.compile(
        loss=tf.keras.losses.MeanSquaredError(), 
        optimizer='adam', 
        metrics=[tf.keras.metrics.MeanSquaredError(), NSE, r_square]
    )

    history = model.fit(
        window.train, 
        epochs=MAX_EPOCHS,
        validation_data=window.val,
        callbacks=[early_stopping]
    )

    return history

In [14]:
# Dense Neural Network
dense = tf.keras.Sequential([
    tf.keras.layers.Dense(units=64, activation='relu'),
    tf.keras.layers.Dense(units=64, activation='relu'),
    tf.keras.layers.Dense(units=64, activation='relu'),
    tf.keras.layers.Dense(units=1)
])

# Convolution Neural Network
conv_model = tf.keras.Sequential([
    tf.keras.layers.Conv1D(filters=64, kernel_size=(CONV_WIDTH,), activation='relu'),
    tf.keras.layers.Dense(units=64, activation='relu'),
    tf.keras.layers.Dense(units=64, activation='relu'),
    tf.keras.layers.Dense(units=1),
])

# LSTM
lstm_model = tf.keras.models.Sequential([
    tf.keras.layers.LSTM(64, return_sequences=True),
    tf.keras.layers.Dense(units=64, activation='relu'),
    tf.keras.layers.Dense(units=64, activation='relu'),
    tf.keras.layers.Dense(units=1)
])

In [15]:
dense_history = compile_and_fit(dense, wide_window)

Epoch 1/20
192/192 [==============================] - 3s 8ms/step - loss: 9.8162 - mean_squared_error: 9.8162 - NSE: -47.1121 - r_square: 0.6567 - val_loss: 0.0308 - val_mean_squared_error: 0.0308 - val_NSE: 0.7242 - val_r_square: 0.8098
Epoch 2/20
192/192 [==============================] - 1s 6ms/step - loss: 0.0185 - mean_squared_error: 0.0185 - NSE: 0.9285 - r_square: 0.9384 - val_loss: 0.0153 - val_mean_squared_error: 0.0153 - val_NSE: 0.8741 - val_r_square: 0.8984
Epoch 3/20
192/192 [==============================] - 1s 6ms/step - loss: 0.0080 - mean_squared_error: 0.0080 - NSE: 0.9672 - r_square: 0.9698 - val_loss: 0.0137 - val_mean_squared_error: 0.0137 - val_NSE: 0.8890 - val_r_square: 0.9121
Epoch 4/20
192/192 [==============================] - 1s 7ms/step - loss: 0.0099 - mean_squared_error: 0.0099 - NSE: 0.9643 - r_square: 0.9695 - val_loss: 0.0117 - val_mean_squared_error: 0.0117 - val_NSE: 0.9009 - val_r_square: 0.9237
Epoch 5/20
192/192 [==============================] - 1s 6ms/step - loss: 0.0046 - mean_squared_error: 0.0046 - NSE: 0.9813 - r_square: 0.9830 - val_loss: 0.0103 - val_mean_squared_error: 0.0103 - val_NSE: 0.9178 - val_r_square: 0.9333
Epoch 6/20
192/192 [==============================] - 1s 7ms/step - loss: 0.0039 - mean_squared_error: 0.0039 - NSE: 0.9853 - r_square: 0.9868 - val_loss: 0.0091 - val_mean_squared_error: 0.0091 - val_NSE: 0.9238 - val_r_square: 0.9376
Epoch 7/20
192/192 [==============================] - 1s 6ms/step - loss: 0.0039 - mean_squared_error: 0.0039 - NSE: 0.9840 - r_square: 0.9859 - val_loss: 0.0107 - val_mean_squared_error: 0.0107 - val_NSE: 0.9181 - val_r_square: 0.9362
Epoch 8/20
192/192 [==============================] - 1s 5ms/step - loss: 0.0044 - mean_squared_error: 0.0044 - NSE: 0.9811 - r_square: 0.9840 - val_loss: 0.0094 - val_mean_squared_error: 0.0094 - val_NSE: 0.9171 - val_r_square: 0.9269

In [28]:
dense_history.history

{'loss': [9.816239356994629,
  0.01847798563539982,
  0.007988509722054005,
  0.009902521036565304,
  0.004649176727980375,
  0.0038982972037047148,
  0.003939403686672449,
  0.004428091458976269],
 'mean_squared_error': [9.816237449645996,
  0.01847798377275467,
  0.007988505996763706,
  0.00990252010524273,
  0.004649178124964237,
  0.00389829627238214,
  0.003939405083656311,
  0.004428092390298843],
 'NSE': [-47.112064361572266,
  0.9285121560096741,
  0.9671807885169983,
  0.9643411040306091,
  0.981322705745697,
  0.9852817058563232,
  0.9840373992919922,
  0.981141984462738],
 'r_square': [0.6566581130027771,
  0.9384255409240723,
  0.9698087573051453,
  0.9694700241088867,
  0.9830126762390137,
  0.9867510795593262,
  0.9859427809715271,
  0.9839809536933899],
 'val_loss': [0.03077438659965992,
  0.015289921313524246,
  0.013692577369511127,
  0.011749721132218838,
  0.010259379632771015,
  0.009104112163186073,
  0.0107455775141716,
  0.009429342113435268],
 'val_mean_squared_error': [0.030774394050240517,
  0.01528992597013712,
  0.013692575506865978,
  0.011749720200896263,
  0.01025938056409359,
  0.009104114025831223,
  0.010745576582849026,
  0.009429342113435268],
 'val_NSE': [0.7242104411125183,
  0.8741458058357239,
  0.8890321850776672,
  0.9008976817131042,
  0.9177848100662231,
  0.9237524271011353,
  0.9181203842163086,
  0.9170836210250854],
 'val_r_square': [0.8098363280296326,
  0.8983720541000366,
  0.9120522737503052,
  0.9237430691719055,
  0.9333170652389526,
  0.9376136660575867,
  0.9362305402755737,
  0.9268515706062317]}

In [16]:
conv_history = compile_and_fit(conv_model, conv_window)

Epoch 1/20
192/192 [==============================] - 3s 7ms/step - loss: 10.2664 - mean_squared_error: 10.2664 - NSE: -48.1765 - r_square: 0.6813 - val_loss: 0.0918 - val_mean_squared_error: 0.0918 - val_NSE: 0.1700 - val_r_square: 0.7351
Epoch 2/20
192/192 [==============================] - 1s 6ms/step - loss: 0.0633 - mean_squared_error: 0.0633 - NSE: 0.7711 - r_square: 0.8738 - val_loss: 0.0468 - val_mean_squared_error: 0.0468 - val_NSE: 0.6052 - val_r_square: 0.8211
Epoch 3/20
192/192 [==============================] - 1s 5ms/step - loss: 0.0307 - mean_squared_error: 0.0307 - NSE: 0.8754 - r_square: 0.9164 - val_loss: 0.0365 - val_mean_squared_error: 0.0365 - val_NSE: 0.7098 - val_r_square: 0.8523
Epoch 4/20
192/192 [==============================] - 1s 5ms/step - loss: 0.0234 - mean_squared_error: 0.0234 - NSE: 0.8959 - r_square: 0.9298 - val_loss: 0.0292 - val_mean_squared_error: 0.0292 - val_NSE: 0.7548 - val_r_square: 0.8568
Epoch 5/20
192/192 [==============================] - 1s 6ms/step - loss: 0.0194 - mean_squared_error: 0.0194 - NSE: 0.9198 - r_square: 0.9465 - val_loss: 0.0348 - val_mean_squared_error: 0.0348 - val_NSE: 0.7133 - val_r_square: 0.8682
Epoch 6/20
192/192 [==============================] - 1s 6ms/step - loss: 0.0190 - mean_squared_error: 0.0190 - NSE: 0.9213 - r_square: 0.9472 - val_loss: 0.0285 - val_mean_squared_error: 0.0285 - val_NSE: 0.7712 - val_r_square: 0.8527
Epoch 7/20
192/192 [==============================] - 1s 6ms/step - loss: 0.0191 - mean_squared_error: 0.0191 - NSE: 0.9219 - r_square: 0.9497 - val_loss: 0.0330 - val_mean_squared_error: 0.0330 - val_NSE: 0.7181 - val_r_square: 0.8704
Epoch 8/20
192/192 [==============================] - 1s 6ms/step - loss: 0.0199 - mean_squared_error: 0.0199 - NSE: 0.9221 - r_square: 0.9432 - val_loss: 0.0335 - val_mean_squared_error: 0.0335 - val_NSE: 0.7457 - val_r_square: 0.8819

In [17]:
lstm_history = compile_and_fit(lstm_model, wide_window)

Epoch 1/20
192/192 [==============================] - 7s 16ms/step - loss: 15.4323 - mean_squared_error: 15.4323 - NSE: -73.1602 - r_square: 0.2509 - val_loss: 0.3078 - val_mean_squared_error: 0.3078 - val_NSE: -1.6652 - val_r_square: 0.1866
Epoch 2/20
192/192 [==============================] - 2s 13ms/step - loss: 0.1723 - mean_squared_error: 0.1723 - NSE: 0.3958 - r_square: 0.5443 - val_loss: 0.2195 - val_mean_squared_error: 0.2195 - val_NSE: -0.8899 - val_r_square: 0.4489
Epoch 3/20
192/192 [==============================] - 2s 13ms/step - loss: 0.0944 - mean_squared_error: 0.0944 - NSE: 0.6691 - r_square: 0.7888 - val_loss: 0.0771 - val_mean_squared_error: 0.0771 - val_NSE: 0.3410 - val_r_square: 0.6439
Epoch 4/20
192/192 [==============================] - 2s 13ms/step - loss: 0.0541 - mean_squared_error: 0.0541 - NSE: 0.8089 - r_square: 0.8837 - val_loss: 0.0555 - val_mean_squared_error: 0.0555 - val_NSE: 0.5107 - val_r_square: 0.7401
Epoch 5/20
192/192 [==============================] - 2s 11ms/step - loss: 0.0326 - mean_squared_error: 0.0326 - NSE: 0.8831 - r_square: 0.9134 - val_loss: 0.0327 - val_mean_squared_error: 0.0327 - val_NSE: 0.7249 - val_r_square: 0.8133
Epoch 6/20
192/192 [==============================] - 2s 9ms/step - loss: 0.0249 - mean_squared_error: 0.0249 - NSE: 0.9094 - r_square: 0.9270 - val_loss: 0.0284 - val_mean_squared_error: 0.0284 - val_NSE: 0.7614 - val_r_square: 0.8475
Epoch 7/20
192/192 [==============================] - 2s 9ms/step - loss: 0.0205 - mean_squared_error: 0.0205 - NSE: 0.9270 - r_square: 0.9389 - val_loss: 0.0261 - val_mean_squared_error: 0.0261 - val_NSE: 0.7814 - val_r_square: 0.8689
Epoch 8/20
192/192 [==============================] - 2s 10ms/step - loss: 0.0180 - mean_squared_error: 0.0180 - NSE: 0.9345 - r_square: 0.9471 - val_loss: 0.0178 - val_mean_squared_error: 0.0178 - val_NSE: 0.8526 - val_r_square: 0.8855
Epoch 9/20
192/192 [==============================] - 3s 13ms/step - loss: 0.0145 - mean_squared_error: 0.0145 - NSE: 0.9489 - r_square: 0.9566 - val_loss: 0.0203 - val_mean_squared_error: 0.0203 - val_NSE: 0.8276 - val_r_square: 0.8853
Epoch 10/20
192/192 [==============================] - 2s 13ms/step - loss: 0.0123 - mean_squared_error: 0.0123 - NSE: 0.9553 - r_square: 0.9621 - val_loss: 0.0140 - val_mean_squared_error: 0.0140 - val_NSE: 0.8810 - val_r_square: 0.9032
Epoch 11/20
192/192 [==============================] - 2s 12ms/step - loss: 0.0099 - mean_squared_error: 0.0099 - NSE: 0.9645 - r_square: 0.9697 - val_loss: 0.0127 - val_mean_squared_error: 0.0127 - val_NSE: 0.8945 - val_r_square: 0.9148
Epoch 12/20
192/192 [==============================] - 2s 12ms/step - loss: 0.0078 - mean_squared_error: 0.0078 - NSE: 0.9705 - r_square: 0.9760 - val_loss: 0.0116 - val_mean_squared_error: 0.0116 - val_NSE: 0.9027 - val_r_square: 0.9219
Epoch 13/20
192/192 [==============================] - 2s 9ms/step - loss: 0.0063 - mean_squared_error: 0.0063 - NSE: 0.9754 - r_square: 0.9792 - val_loss: 0.0111 - val_mean_squared_error: 0.0111 - val_NSE: 0.9088 - val_r_square: 0.9278
Epoch 14/20
192/192 [==============================] - 2s 9ms/step - loss: 0.0060 - mean_squared_error: 0.0060 - NSE: 0.9767 - r_square: 0.9828 - val_loss: 0.0100 - val_mean_squared_error: 0.0100 - val_NSE: 0.9204 - val_r_square: 0.9335
Epoch 15/20
192/192 [==============================] - 2s 10ms/step - loss: 0.0051 - mean_squared_error: 0.0051 - NSE: 0.9801 - r_square: 0.9840 - val_loss: 0.0092 - val_mean_squared_error: 0.0092 - val_NSE: 0.9222 - val_r_square: 0.9372
Epoch 16/20
192/192 [==============================] - 2s 11ms/step - loss: 0.0044 - mean_squared_error: 0.0044 - NSE: 0.9822 - r_square: 0.9858 - val_loss: 0.0100 - val_mean_squared_error: 0.0100 - val_NSE: 0.9090 - val_r_square: 0.9306
Epoch 17/20
192/192 [==============================] - 3s 13ms/step - loss: 0.0051 - mean_squared_error: 0.0051 - NSE: 0.9802 - r_square: 0.9848 - val_loss: 0.0088 - val_mean_squared_error: 0.0088 - val_NSE: 0.9251 - val_r_square: 0.9342
Epoch 18/20
192/192 [==============================] - 2s 13ms/step - loss: 0.0048 - mean_squared_error: 0.0048 - NSE: 0.9802 - r_square: 0.9838 - val_loss: 0.0101 - val_mean_squared_error: 0.0101 - val_NSE: 0.9252 - val_r_square: 0.9299
Epoch 19/20
192/192 [==============================] - 3s 13ms/step - loss: 0.0045 - mean_squared_error: 0.0045 - NSE: 0.9814 - r_square: 0.9867 - val_loss: 0.0092 - val_mean_squared_error: 0.0092 - val_NSE: 0.9281 - val_r_square: 0.9355

In [18]:
val_performance = {}
performance = {}

In [19]:
val_performance['Dense'] = dense.evaluate(wide_window.val)

55/55 [==============================] - 0s 3ms/step - loss: 0.0094 - mean_squared_error: 0.0094 - NSE: 0.9239 - r_square: 0.9316

In [20]:
performance['Dense'] = dense.evaluate(wide_window.test, verbose=0)

In [21]:
val_performance['Conv'] = conv_model.evaluate(conv_window.val)

55/55 [==============================] - 0s 3ms/step - loss: 0.0335 - mean_squared_error: 0.0335 - NSE: 0.7331 - r_square: 0.8812

In [22]:
performance['Conv'] = conv_model.evaluate(conv_window.test, verbose=0)

In [23]:
val_performance['LSTM'] = lstm_model.evaluate(wide_window.val)

55/55 [==============================] - 0s 5ms/step - loss: 0.0092 - mean_squared_error: 0.0092 - NSE: 0.9278 - r_square: 0.9349

In [24]:
performance['LSTM'] = lstm_model.evaluate(wide_window.test, verbose=0)

In [25]:
val_performance

{'Dense': [0.00942934025079012,
  0.009429342113435268,
  0.9239160418510437,
  0.9315859079360962],
 'Conv': [0.0335293747484684,
  0.0335293747484684,
  0.7331186532974243,
  0.8811503052711487],
 'LSTM': [0.009173501282930374,
  0.009173505008220673,
  0.9277848601341248,
  0.9348770380020142]}

In [26]:
performance

{'Dense': [0.0006408169283531606,
  0.0006408169283531606,
  0.9669933319091797,
  0.9687368273735046],
 'Conv': [0.010064207948744297,
  0.010064207948744297,
  0.4383182227611542,
  0.9155910611152649],
 'LSTM': [0.000983240082859993,
  0.000983240082859993,
  0.9426574110984802,
  0.9713611602783203]}